#!/bin/sh

# Deployed stack
# - NestJS
# - Prisma
# - MongoDB
# - Redis
# - Mailpit

printf "Project name: "
read -r projectName

# Install and configure Nx
yarn global add nx
npx create-nx-workspace "$projectName" \
  --interactive=false \
  --workspaceType=integrated \
  --preset=apps \
  --skipGit=true \
  --pm=yarn \
  --nxCloud=false

cd "$projectName" || exit 1

# Install NestJS
yarn add -D @nx/nest
npx nx g @nx/nest:app backend \
  --unitTestRunner jest \
  --directory apps/backend \
  --projectNameAndRootFormat as-provided \
  --strict true \
  --e2eTestRunner none

# Install Prisma
yarn add -D @nx-tools/nx-prisma

npx nx g @nx/nest:lib db \
  --unitTestRunner=none \
  --directory libs/db \
  --projectNameAndRootFormat as-provided
npx nx g @nx-tools/nx-prisma:init db

cat << EOF > apps/backend/Dockerfile
# This file is generated by Nx.
#
# Build the docker image with \`npx nx docker-build backend\`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with \`docker run -p 3000:3000 -t backend\`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system backend && \
          adduser --system -G backend backend

COPY dist/apps/backend backend
COPY libs/db/prisma/schema.prisma backend/schema.prisma
RUN chown -R backend:backend .

# You can remove this install step if you build with \`--bundle\` option.
# The bundled output will include external dependencies.
RUN npm --prefix backend --omit=dev -f install

RUN cd backend && npx prisma generate

CMD [ "node", "backend/main.js" ]
EOF

cat << EOF > docker-compose.yaml
version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '${FORWARD_DB_PORT:-27017}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: \${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: \${DB_PASSWORD}
    volumes:
      - 'nest-mongo:/data/db'
    networks:
      - nest
  redis:
    image: 'redis:alpine'
    ports:
      - '\${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'nest-redis:/data'
    networks:
      - nest
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '\${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '\${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - nest

networks:
  nest:
    driver: bridge
volumes:
  nest-mongo:
    driver: local
  nest-redis:
    driver: local

EOF

cat << EOF > .env
DB_USERNAME=nestjs
DB_PASSWORD=nestjs
DB_DATABASE=nestjs
DB_HOST=localhost
EOF

echo ".env" >> .gitignore

cp .env .env.example
mkdir -p .github/workflows
cat << EOF > .github/workflows/check.yml
name: 'Check project'

on:
  pull_request:
    branches:
      - staging
      - main

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '\${{ github.workflow }} @ \${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies 📦
        run: yarn install
      - name: Link check 🗒️
        run: npx nx run-many -t lint
      - name: Running tests 🧪
        run: npx nx run-many -t test
      - name: Testing production build 🏗️
        run: npx nx run-many -t build
EOF

cat << EOF > README.md
## Prerequisites
Install the yarn dependencies
\`\`\`
yarn install
\`\`\`

## Development

### Directory structure
\`\`\`
├── apps
│   └── backend
├── libs
│   ├── db
├──.env
├──.env.example
├──docker-compose.yml
├──dist
\`\`\`
The apps directory contains the applications.

The libs directory contains the modules used by the frontend and/or the backend.

By default, there is one module: **db**.
* **db**: contains the prisma schema and the generated prisma client used by the backend.

> **Important**
> In a library, a component, to be used outside the library, must be exported in the index.ts file.

### Start the development servers
In order to start both the backend and the frontend, run the following command:
\`\`\`
nx run-many -t serve
\`\`\`

The backend will be available at http://localhost:3000/api.

In order to start the database servers, run the following command:
\`\`\`
docker compose up
\`\`\`
It will start the following servers:
* mongodb
  * Host: localhost
  * Port: 27017
  * User: {FROM .env}
  * Password: {FROM .env}
  * Database: {FROM .env}
* redis
  * Host: localhost
  * Port: 6379
* mailpit
  * Host: localhost
  * Port: 1025


### Linting
\`\`\`
nx run-many -t lint
\`\`\`

### Testing
\`\`\`
nx run-many -t test
\`\`\`

## Production
To build the project run:
\`\`\`
nx run-many -t build
\`\`\`
The build artifacts will be stored in the \`dist/\` directory, ready to be deployed.
 \\

 \\
<a alt="Nx logo" href="https://nx.dev" target="_blank" rel="noreferrer"><img src="https://raw.githubusercontent.com/nrwl/nx/master/images/nx-logo.png" width="45"></a>

✨ **This workspace has been generated by [Nx, a Smart, fast and extensible build system.](https://nx.dev)** ✨


## Generate code

If you happen to use Nx plugins, you can leverage code generators that might come with it.

Run \`nx list\` to get a list of available plugins and whether they have generators. Then run \`nx list <plugin-name>\` to see what generators are available.

Learn more about [Nx generators on the docs](https://nx.dev/plugin-features/use-code-generators).

## Running tasks

To execute tasks with Nx use the following syntax:

\`\`\`
nx <target> <project> <...options>
\`\`\`

You can also run multiple targets:

\`\`\`
nx run-many -t <target1> <target2>
\`\`\`

..or add \`-p\` to filter specific projects

\`\`\`
nx run-many -t <target1> <target2> -p <proj1> <proj2>
\`\`\`

Targets can be defined in the \`package.json\` or \`projects.json\`. Learn more [in the docs](https://nx.dev/core-features/run-tasks).
EOF